# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
toggle_key: RIGHT_ALT

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
  
  - trigger: ":lenny"
    replace: "( Õ°¬∞ Õú ñ Õ°¬∞)"

  - trigger: ":chad"
    replace: "üí™üòéü¶æ üçóü¶µ"

  - trigger: ":uwu"
    replace: "(‚Ä≤ÍàçœâÍàç‚Äµ)"

  - trigger: ":navy"
    replace: "What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little \"clever\" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo."

  - trigger: ":vaporeon"
    replace: "Hey guys, did you know that in terms of male human and female Pok√©mon breeding, Vaporeon is the most compatible Pok√©mon for humans? Not only are they in the field egg group, which is mostly comprised of mammals, Vaporeon are an average of 3‚Äù03‚Äô tall and 63.9 pounds, this means they‚Äôre large enough to be able handle human dicks, and with their impressive Base Stats for HP and access to Acid Armor, you can be rough with one. Due to their mostly water based biology, there‚Äôs no doubt in my mind that an aroused Vaporeon would be incredibly wet, so wet that you could easily have sex with one for hours without getting sore. They can also learn the moves Attract, Baby-Doll Eyes, Captivate, Charm, and Tail Whip, along with not having fur to hide nipples, so it‚Äôd be incredibly easy for one to get you in the mood. With their abilities Water Absorb and Hydration, they can easily recover from fatigue with enough water. No other Pok√©mon comes close to this level of compatibility. Also, fun fact, if you pull out enough, you can make your Vaporeon turn white. Vaporeon is literally built for human dick. Ungodly defense stat+high HP pool+Acid Armor means it can take cock all day, all shapes and sizes and still come for more"

  - trigger: ":dorime"
    image_path: "D:\\screenshots\\espanso\\dorime.jpg"

  - trigger: ":code"
    replace: "{{vscode}}"
    vars:
      - name: vscode
        type: shell
        params:
          cmd: "code"
  - trigger: ":rootex"
    replace: "{{rootex}}"
    vars:
      - name: rootex
        type: shell
        params:
          cmd: "start devenv D:\\SDSLabs\\Rootex\\build\\Rootex.sln"
  - trigger: ":crab"
    replace: "ü¶Äü¶Äü¶Ä"
  - trigger: ":smirk"
    replace: "https://i.imgur.com/6pTbZVb.jpg"
  - trigger: ":..."
    replace: "https://i.imgur.com/bVLmMv1.jpg"
  - trigger: ":surprise"
    replace: "https://i.imgur.com/5Z0cKKX.jpg"
  - trigger: ":delete"
    replace: "https://i.redd.it/t4vs3xsqnoa51.jpg"
  - trigger: ":teehee"
    replace: "https://i.imgur.com/edjx3q2.jpg"
  - trigger: ":police"
    replace: "https://i.imgur.com/o8juuqk.jpg"
  - trigger: ":kya"
    replace: "https://i.imgur.com/W4r6REA.png"
  - trigger: ":smug"
    replace: "https://i.imgur.com/M0vLezd.jpg"
  - trigger: ":fap"
    replace: "https://i.imgur.com/bIuS1v7.jpg"
  - trigger: ":frown"
    replace: "https://i.imgur.com/sbNrlUc.png"
  - trigger: ":kaguya"
    replace: "https://i.imgur.com/NyJI1Jc.png"
  - trigger: ":bigsmile"
    replace: "https://i.imgur.com/nW3prVY.png"
  - trigger: ":kashira"
    replace: "https://i.imgur.com/oKSemXb.png"
  - trigger: ":wut"
    replace: "https://i.imgur.com/URuoatF.png"
  - trigger: ":disgust"
    replace: "https://imgur.com/SVVUw0f"
  - trigger: ":angry"
    replace: "https://i.imgur.com/xLjurID.png"
  - trigger: ":strip"
    replace: "https://i.imgur.com/jVFUI34.jpg"
  - trigger: ":nanacry"
    replace: "https://i.imgur.com/nTbBSXm.png"
  - trigger: ":nanahappy"
    replace: "https://i.imgur.com/MNGV3sN.png"
  - trigger: ":okpedo"
    replace: "https://i.imgur.com/AaESNEP.png"
  - trigger: ":musicfire"
    replace: "https://i.imgur.com/mE6np63.gif"
